@echo off
set BUCKET_NAME="%%BUCKET_NAME%%"
set OBJECT_NAME="%%OBJECT_NAME%%"
set S3_ENDPOINT_URL="%%S3_ENDPOINT_URL%%"
s3 put %BUCKET_NAME%/%OBJECT_NAME% filename="%%INPUT_FILE%%" %%METADATA_PROPERTIES%%
